Seccion 30
Cristianpan/Curso-web pull request #19
Opened 2023-05-03 04:46 UTC by Cristianpan

2023-05-03 22:57 UTC, LUGAMAFE requested changes

2023-05-03 22:57 UTC, LUGAMAFE commented on bienesRaices/backup/bienesraices.dump
Este archivo Cristian porfa no use .dump para exportar la base de datos utiliza .sql de igual manera el archivo esta mal ya que primero crea la tabla propiedades y luego la de vendores pero la tabla de propiedades esta haciendo referencia a la de vendedores cuando todavia no existe. El orden de las cosas en este archivo importa. 

De igual manera estas usando phpmyadmin? trata de exportar tu sql desde ahi porfavor.
cosas como LOCK TABLES `vendedores` WRITE;
o 
UNLOCK TABLES; no son propias de mysql

2023-05-03 23:45 UTC, Cristianpan commented on bienesRaices/backup/bienesraices.dump
De acuerdo, no sabía que no era buena práctica. De igual manera, no utilizaba phomyadmin, utilizo tablePlus entonces creo que por eso agrego lo que mencionas. Tendré más cuidado de ahora en adelante

2023-05-04 05:05 UTC, LUGAMAFE approved these changes
Listo cristian muchas gracias

2023-05-04 21:07 UTC, jfer1990 approved these changes

2023-05-04 23:40 UTC, merged